version: 2.1

jobs:
  build:
    parameters:
      image:
        description: "The Docker image to be used"
        type: string
    working_directory: ~/repo
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
            go mod download
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.49.0
            golangci-lint --version
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run lint
          command: golangci-lint
      - run:
          name: Run tests
          command: go test -race -count 75 ./...

workflows:
  build:
    jobs:
      - build:
          image: "cimg/go:1.18.5"
          name: "go1.18.5"
      - build:
          image: "cimg/go:1.19.0"
          name: "go1.19.0"
